name: RELEASE
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install deps
        run: npm ci

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@djadriano'

      - name: Run NX commands
        run: |
          npx nx affected --target lint --parallel 3
          npx nx affected --target test --parallel 3 --ci
          npx nx affected --target build --parallel 3

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
